// This file has been autogenerated from a class added in the UI designer.

using System;
using UI.Utils;
using ReactiveUI;
using System.Reactive.Linq;
using System.Reactive.Disposables;
using System.Linq;
using UI.ViewDataSources;
using UI.ViewDelegates;
using UI.ViewModels;

namespace UI.ViewControllers
{
    public partial class ViewController : ViewControllerBase<ViewModel>
	{
		public ViewController(IntPtr handle) : base(handle)
		{
            ViewModel = new ViewModel();
            this.WhenActivated(disposables =>
            {
                this.WhenAnyValue(x => x.ViewModel)
                    .Where(x => x != null)
                    .Do(PopulateFromViewModel)
                    .Subscribe()
                    .DisposeWith(disposables);
            });
        }

        private void PopulateFromViewModel(ViewModel viewModel)
        {
            _favoriteOutlineView.DataSource = new FavoriteOutlineViewDataSource(viewModel.StationData, _favoriteOutlineView);
            _favoriteOutlineView.Delegate = new FavoriteOutlineDelegate((FavoriteOutlineViewDataSource)_favoriteOutlineView.DataSource);
        }
    }
}
