// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;
using UI.Utils;

namespace UI
{
	public partial class ViewController : ViewControllerBase<ViewModel>
	{
		public ViewController(IntPtr handle) : base(handle)
		{
		}
	}
}
