// This file has been autogenerated from a class added in the UI designer.

using Foundation;
using AppKit;
using UI.Model;

namespace UI
{
    public partial class FavoriteOutlineDelegate : NSOutlineViewDelegate
    {
        #region Constants
        private const string StationNameCell = @"StationNameCell";
        private const string DestinationCell = @"DestinationCell";
        private const string EstimatedArrivalTimeCell = @"EstimatedArrivalTimeCell";
        #endregion

        #region Private Variables
        private FavoriteOutlineViewDataSource DataSource;
        #endregion

        #region Constructors
        public FavoriteOutlineDelegate(FavoriteOutlineViewDataSource datasource)
        {
            this.DataSource = datasource;
        }
        #endregion

        #region Override Methods
        public override NSView GetView(NSOutlineView outlineView, NSTableColumn tableColumn, NSObject item)
        {
            NSTextField view = null;

            // Setup view based on the column selected
            switch (tableColumn.Identifier)
            {
                case "StationNameColumn":
                    view = (NSTextField)outlineView.MakeView(StationNameCell, this);
                    if (view == null)
                    {
                        view = new NSTextField();
                        view.Identifier = StationNameCell;
                        view.BackgroundColor = NSColor.Clear;
                        view.Bordered = false;
                        view.Selectable = false;
                        view.Editable = false;
                    }

                    // Cast item
                    var stationModelStationDesc = item as FavoriteStation;
                    var Stationfullname = stationModelStationDesc?.Stationfullname;
                    view.StringValue = Stationfullname == null ? ((StationData)item).Traincode : Stationfullname;
                    break;
                case "DestinationColumn":
                    view = (NSTextField)outlineView.MakeView(DestinationCell, this);
                    if (view == null)
                    {
                        view = new NSTextField();
                        view.Identifier = StationNameCell;
                        view.BackgroundColor = NSColor.Clear;
                        view.Bordered = false;
                        view.Selectable = false;
                        view.Editable = false;
                    }

                    // Cast item
                    var stationDataDestination = item as StationData;
                    var Destination = stationDataDestination?.Destination;
                    view.StringValue = Destination == null ? string.Empty : Destination;
                    break;
                case "EstimatedArrivalTimeColumn":
                    view = (NSTextField)outlineView.MakeView(EstimatedArrivalTimeCell, this);
                    if (view == null)
                    {
                        view = new NSTextField();
                        view.Identifier = StationNameCell;
                        view.BackgroundColor = NSColor.Clear;
                        view.Bordered = false;
                        view.Selectable = false;
                        view.Editable = false;
                    }

                    // Cast item
                    var stationDataExparrival = item as StationData;
                    var Exparrival = stationDataExparrival?.Exparrival;
                    view.StringValue = Exparrival == null ? string.Empty : Exparrival;
                    break;
            }

            return view;
        }

        public override bool ShouldSelectItem(NSOutlineView outlineView, NSObject item)
        {
            var favoriteStation = item as FavoriteStation;
            return favoriteStation != null ? favoriteStation.StationData.Count > 0 ? true : false : false;
        }
        #endregion
    }
}
